/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import formingWords.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class formingWordsGUI extends javax.swing.JFrame {

    /**
     * Creates new form formingWordsGUI
     */
    operationFormingWords op = new operationFormingWords();

    public String originalWord = op.wordsOriginal(op.words());
    public String showDisform = "";
    public int Score = 100;
    public String answerUserGlobal = "";
    public boolean band1 = false;
    public boolean band2 = false;
    public boolean band3 = false;
    public boolean band4 = false;
    public boolean band5 = false;
    public boolean band6 = false;
    public boolean band7 = false;
    public boolean band8 = false;

    public formingWordsGUI() {
        initComponents();
        showDisform = op.disformArrayWord(op.words2(originalWord));
        showDisformingLabel.setText(showDisform);
        showScore.setText(String.valueOf(Score));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        panelOfformingWords = new javax.swing.JPanel();
        solutionsButton = new javax.swing.JButton();
        finishGame = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        formingTitleLabel = new javax.swing.JLabel();
        scoreTitleLabel = new javax.swing.JLabel();
        showDisformingLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        showScore = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOfformingWords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        solutionsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        solutionsButton.setText("Solve");
        solutionsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        solutionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionsButtonActionPerformed(evt);
            }
        });

        finishGame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        finishGame.setText("End Game");
        finishGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finishGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGameActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        formingTitleLabel.setBackground(new java.awt.Color(204, 204, 204));
        formingTitleLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        formingTitleLabel.setText(" Forming Words");

        scoreTitleLabel.setBackground(new java.awt.Color(204, 204, 204));
        scoreTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scoreTitleLabel.setText("Score:");

        showDisformingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showDisformingLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jTextField7.setEditable(false);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        showScore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelOfformingWordsLayout = new javax.swing.GroupLayout(panelOfformingWords);
        panelOfformingWords.setLayout(panelOfformingWordsLayout);
        panelOfformingWordsLayout.setHorizontalGroup(
            panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOfformingWordsLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scoreTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showScore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addComponent(showDisformingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(solutionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 98, Short.MAX_VALUE))
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finishGame)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(formingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOfformingWordsLayout.setVerticalGroup(
            panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(formingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showDisformingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOfformingWordsLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(solutionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(panelOfformingWordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(finishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(showScore, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOfformingWordsLayout.createSequentialGroup()
                        .addComponent(scoreTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOfformingWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOfformingWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void finishGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGameActionPerformed
        // TODO add your handling code here:
        try {
            setVisible(false);
            this.dispose();//close 
            mainGUI main = new mainGUI();//new instance for a new game
            main.setTitle("Programming Project");
            main.setVisible(true);
            main.setLocationRelativeTo(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }

    }//GEN-LAST:event_finishGameActionPerformed

    private void solutionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionsButtonActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(rootPane, "The word is: " + originalWord);
            showDisformingLabel.setText("");
            showDisform = op.disformArrayWord(op.words());
            originalWord = op.wordsOriginal(op.words());
            showDisform = op.disformArrayWord(op.words2(originalWord));
            showDisformingLabel.setText(showDisform);
            Score = Score - 10;
            showScore.setText(String.valueOf(Score));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_solutionsButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band1 == false) {
                String textOne = jTextField1.getText();
                if (jTextField1.getText().length() == 1) {
                    evt.consume();
                }
                char firtChar = originalWord.charAt(0);
                if (textOne.equalsIgnoreCase(String.valueOf(firtChar))) {
                    jTextField1.setEditable(false);
                    jTextField2.setEditable(true);
                    answerUserGlobal += textOne;
                    textOne = "";
                    band1 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField1.addKeyListener(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band2 == false) {
                String textTwo = jTextField2.getText();
                if (jTextField2.getText().length() == 1) {
                    evt.consume();
                }
                char WordChar = originalWord.charAt(1);
                if (textTwo.equalsIgnoreCase(String.valueOf(WordChar))) {
                    answerUserGlobal += textTwo;
                    jTextField2.setEditable(false);
                    jTextField3.setEditable(true);
                    textTwo = "";
                    band2 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band3 == false) {
                String textThree = jTextField3.getText();
                if (jTextField3.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(2);
                if (textThree.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textThree;
                    jTextField3.setEditable(false);
                    jTextField4.setEditable(true);
                    textThree = "";
                    band3 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band4 == false) {
                String textFour = jTextField4.getText();
                if (jTextField4.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(3);
                if (textFour.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textFour;
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(true);
                    textFour = "";
                    band4 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField2.setEditable(false);
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(false);
                    showDisformingLabel.setText("");
                    showDisform = op.disformArrayWord(op.words());
                    originalWord = op.wordsOriginal(op.words());
                    showDisform = op.disformArrayWord(op.words2(originalWord));
                    showDisformingLabel.setText(showDisform);
                    answerUserGlobal = "";
                    band1 = false;
                    band2 = false;
                    band3 = false;
                    band4 = false;
                    band5 = false;
                    band6 = false;
                    band7 = false;
                    band8 = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band5 == false) {
                String textFive = jTextField5.getText();
                if (jTextField5.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(4);
                if (textFive.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textFive;
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(true);
                    textFive = "";
                    band5 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField2.setEditable(false);
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(false);
                    showDisformingLabel.setText("");
                    showDisform = op.disformArrayWord(op.words());
                    originalWord = op.wordsOriginal(op.words());
                    showDisform = op.disformArrayWord(op.words2(originalWord));
                    showDisformingLabel.setText(showDisform);
                    answerUserGlobal = "";
                    band1 = false;
                    band2 = false;
                    band3 = false;
                    band4 = false;
                    band5 = false;
                    band6 = false;
                    band7 = false;
                    band8 = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band6 == false) {
                String textSix = jTextField6.getText();
                if (jTextField6.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(5);
                if (textSix.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textSix;
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(true);
                    textSix = "";
                    band6 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField2.setEditable(false);
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(false);
                    showDisformingLabel.setText("");
                    showDisform = op.disformArrayWord(op.words());
                    originalWord = op.wordsOriginal(op.words());
                    showDisform = op.disformArrayWord(op.words2(originalWord));
                    showDisformingLabel.setText(showDisform);
                    answerUserGlobal = "";
                    band1 = false;
                    band2 = false;
                    band3 = false;
                    band4 = false;
                    band5 = false;
                    band6 = false;
                    band7 = false;
                    band8 = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band7 == false) {
                String textSeven = jTextField7.getText();
                if (jTextField7.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(6);
                if (textSeven.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textSeven;
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(true);
                    textSeven = "";
                    band7 = true;

                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField2.setEditable(false);
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(false);
                    showDisformingLabel.setText("");
                    showDisform = op.disformArrayWord(op.words());
                    originalWord = op.wordsOriginal(op.words());
                    showDisform = op.disformArrayWord(op.words2(originalWord));
                    showDisformingLabel.setText(showDisform);
                    answerUserGlobal = "";
                    band1 = false;
                    band2 = false;
                    band3 = false;
                    band4 = false;
                    band5 = false;
                    band6 = false;
                    band7 = false;
                    band8 = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        try {
            char c = evt.getKeyChar();
            if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
                evt.consume();
            }
            if (band8 == false) {
                String textEight = jTextField8.getText();
                if (jTextField8.getText().length() == 1) {
                    evt.consume();
                }
                char wordChar = originalWord.charAt(7);
                if (textEight.equalsIgnoreCase(String.valueOf(wordChar))) {
                    answerUserGlobal += textEight;
                    jTextField8.setEditable(false);
                    textEight = "";
                    band8 = true;
                }
                if (answerUserGlobal.equalsIgnoreCase(originalWord)) {
                    JOptionPane.showMessageDialog(rootPane, "The entered word is correct");
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField1.setEditable(true);
                    jTextField2.setEditable(false);
                    jTextField4.setEditable(false);
                    jTextField5.setEditable(false);
                    jTextField6.setEditable(false);
                    jTextField7.setEditable(false);
                    jTextField8.setEditable(false);
                    showDisformingLabel.setText("");
                    showDisform = op.disformArrayWord(op.words());
                    originalWord = op.wordsOriginal(op.words());
                    showDisform = op.disformArrayWord(op.words2(originalWord));
                    showDisformingLabel.setText(showDisform);
                    answerUserGlobal = "";
                    band1 = false;
                    band2 = false;
                    band3 = false;
                    band4 = false;
                    band5 = false;
                    band6 = false;
                    band7 = false;
                    band8 = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        try {
             JOptionPane.showMessageDialog(null, "1. All the words shown are referring to computer science"
                    + "\n"
                    + "2. Analyze well each letter that will enter to avoid losing points"
                    + "\n"
                    + "3. Consider if losing 10 points to change the word is better than trying to get the word right"
                    + "\n"
                    + "If you want to exit the game press the \"end game\" button");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishGame;
    private javax.swing.JLabel formingTitleLabel;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel panelOfformingWords;
    private javax.swing.JLabel scoreTitleLabel;
    public javax.swing.JLabel showDisformingLabel;
    private javax.swing.JLabel showScore;
    private javax.swing.JButton solutionsButton;
    // End of variables declaration//GEN-END:variables
}
