/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import sumNumbers.OperationSumNumbers;

/**
 *
 * @author Jasson
 */
public class sumNumberGUI extends javax.swing.JFrame {

    /**
     * Creates new form sumNumberGUI
     */
    OperationSumNumbers action = new OperationSumNumbers();
    //initialize the variables
    int numAttempts = action.attempts();
    int correctAttempts = action.correctAttempts();
    int failledAttempts = action.failedatttempts();
    int[] arraysNumbers = action.numRandom();

    public sumNumberGUI() {
        initComponents();
    }

    private void jButton1_compareActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            numAttempts++;//when starting, an attempt is added
            //the number entered by the user is extracted to a variable
            int numberUser = Integer.parseInt(jTextField1_numberUser.getText());
            //the necessary variables are passed through parameters in the method that compares the numbers
            boolean trueOrFalse = action.addingNumbers(arraysNumbers, numberUser, numAttempts);
            //depends what returned by the previous method adds a correct or failed attempt
            if (trueOrFalse == true) {
                correctAttempts++;
            } else {
                failledAttempts++;
            }
            jTextField1_numberUser.setText("");//textfield numberUser set the text with nothing
            arraysNumbers = action.numRandom();
            jLabel1_correctAttempts.setText(String.valueOf(correctAttempts));//the label of correctAttemps set the text of the variable correctAtempts but this variable have to convert in String
            jLabel3_attempts.setText(String.valueOf(numAttempts));//the label of atempts set the text of the vairable numAttempts
            jLabel2_failedAttempts.setText(String.valueOf(failledAttempts));//failedAttempts set the text of the variable failledAttemps
            if (numAttempts % 2 == 0) {//if numAttempts mod 2 equal 0 it mean that numAttempts is pair
                jLabel1_numRandom1.setText("¿?");//labe1 of numRandom set the text "¿?"
                jLabel2_numRandom2.setText(String.valueOf(arraysNumbers[1]));//
            } else {
                jLabel2_numRandom2.setText("¿?");
                jLabel1_numRandom1.setText(String.valueOf(arraysNumbers[0]));
            }
            jLabel1_result.setText(String.valueOf(arraysNumbers[2]));
            if (correctAttempts == 15)//until correctAttempts=15 the game is finished
            {
                setVisible(false);//this jframe is hidden
                this.dispose();//close
                mainGUI main = new mainGUI();//new mainGUI
                main.setTitle("Programming Project");
                main.setVisible(true);
                main.setLocationRelativeTo(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sumNumber_TextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2_frame = new javax.swing.JPanel();
        jLabel1_numRandom1 = new javax.swing.JLabel();
        jLabel1_sum = new javax.swing.JLabel();
        jLabel2_numRandom2 = new javax.swing.JLabel();
        jLabel3_equals = new javax.swing.JLabel();
        jLabel1_result = new javax.swing.JLabel();
        correctAttempts_Label = new javax.swing.JLabel();
        jLabel1_correctAttempts = new javax.swing.JLabel();
        failedAttempts_Label = new javax.swing.JLabel();
        jLabel2_failedAttempts = new javax.swing.JLabel();
        attempts_Label = new javax.swing.JLabel();
        jLabel3_attempts = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        againButton = new javax.swing.JButton();
        jLabel1_numberUser = new javax.swing.JLabel();
        jTextField1_numberUser = new javax.swing.JTextField();
        jButton1_compare = new javax.swing.JButton();
        finishGameButton = new javax.swing.JButton();
        jLabel_sumNumero = new javax.swing.JLabel();

        sumNumber_TextArea.setColumns(20);
        sumNumber_TextArea.setRows(5);
        jScrollPane1.setViewportView(sumNumber_TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_numRandom1.setText("¿?");

        jLabel1_sum.setText("+");

        jLabel2_numRandom2.setText(String.valueOf(arraysNumbers[1]));

        jLabel3_equals.setText("=");

        jLabel1_result.setText(String.valueOf(arraysNumbers[2]));

        correctAttempts_Label.setText("Successful sums:");

        jLabel1_correctAttempts.setText(String.valueOf(correctAttempts));

        failedAttempts_Label.setText(" Unsuccessful sums:");

        jLabel2_failedAttempts.setText(String.valueOf(failledAttempts));

        attempts_Label.setText("Attempts:");

        jLabel3_attempts.setText(String.valueOf(numAttempts));

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        againButton.setText(" Change numbers");
        againButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againButtonActionPerformed(evt);
            }
        });

        jLabel1_numberUser.setText(" Enter the missing number in the equation");

        jTextField1_numberUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_numberUserActionPerformed(evt);
            }
        });

        jButton1_compare.setText("Compare");
        jButton1_compare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_compareActionPerformed(evt);
            }
        });

        finishGameButton.setText(" End Game");
        finishGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGameButtonActionPerformed(evt);
            }
        });

        jLabel_sumNumero.setText("Adding Numbers");

        javax.swing.GroupLayout jPanel2_frameLayout = new javax.swing.GroupLayout(jPanel2_frame);
        jPanel2_frame.setLayout(jPanel2_frameLayout);
        jPanel2_frameLayout.setHorizontalGroup(
            jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_frameLayout.createSequentialGroup()
                        .addComponent(correctAttempts_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1_correctAttempts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2_frameLayout.createSequentialGroup()
                        .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                                .addComponent(helpButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finishGameButton))
                            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1_numRandom1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1_sum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2_numRandom2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3_equals)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1_result, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2_frameLayout.createSequentialGroup()
                                        .addComponent(jTextField1_numberUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1_compare))
                                    .addComponent(jLabel1_numberUser)))
                            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                                .addComponent(attempts_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3_attempts)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                                .addComponent(jLabel_sumNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(againButton)))
                        .addContainerGap())
                    .addGroup(jPanel2_frameLayout.createSequentialGroup()
                        .addComponent(failedAttempts_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_failedAttempts)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2_frameLayout.setVerticalGroup(
            jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_frameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sumNumero)
                    .addComponent(againButton))
                .addGap(28, 28, 28)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_numRandom1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_numRandom2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_sum)
                    .addComponent(jLabel1_result)
                    .addComponent(jLabel1_numberUser)
                    .addComponent(jLabel3_equals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_numberUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_compare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctAttempts_Label)
                    .addComponent(jLabel1_correctAttempts))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(failedAttempts_Label)
                    .addComponent(jLabel2_failedAttempts))
                .addGap(18, 18, 18)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attempts_Label)
                    .addComponent(jLabel3_attempts))
                .addGap(36, 36, 36)
                .addGroup(jPanel2_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(finishGameButton))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void againButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againButtonActionPerformed
        try {
            arraysNumbers = action.numRandom();//call random Number
            numAttempts++;//attempts +1
            if (numAttempts % 2 == 0) {//if residue is cero
                jLabel1_numRandom1.setText("¿?");
                jLabel2_numRandom2.setText(String.valueOf(arraysNumbers[1]));
            } else {
                jLabel2_numRandom2.setText("¿?");
                jLabel1_numRandom1.setText(String.valueOf(arraysNumbers[0]));
            }
            jLabel1_result.setText(String.valueOf(arraysNumbers[2]));
            failledAttempts++;//failedAttempts sum 1
            jLabel3_attempts.setText(String.valueOf(numAttempts));
            jLabel2_failedAttempts.setText(String.valueOf(failledAttempts)); //set the text of label failedAttempts 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }

    }//GEN-LAST:event_againButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        try {
            action.helpMe();//call the method helpme
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }

    }//GEN-LAST:event_helpButtonActionPerformed

    private void jTextField1_numberUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_numberUserActionPerformed

    }//GEN-LAST:event_jTextField1_numberUserActionPerformed
    /*
    private void jButton1_compareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_compareActionPerformed

    }//GEN-LAST:event_jButton1_compareActionPerformed
*/
    private void finishGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGameButtonActionPerformed
        try {
            JOptionPane.showMessageDialog(null, String.valueOf("Attempts made: " + numAttempts + " "
                    + "\n"
                    + "Right attempts: " + correctAttempts + " "
                    + "\n"
                    + "Failed attempts: " + failledAttempts));//show all the attempts
            setVisible(false);
            this.dispose();//close 
            mainGUI main = new mainGUI();//new instance for a new game
            main.setTitle("Programming Project");
            main.setVisible(true);
            main.setLocationRelativeTo(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error has occured!");
        }

    }//GEN-LAST:event_finishGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton againButton;
    private javax.swing.JLabel attempts_Label;
    private javax.swing.JLabel correctAttempts_Label;
    private javax.swing.JLabel failedAttempts_Label;
    private javax.swing.JButton finishGameButton;
    private javax.swing.JButton helpButton;
    public javax.swing.JButton jButton1_compare;
    private javax.swing.JLabel jLabel1_correctAttempts;
    private javax.swing.JLabel jLabel1_numRandom1;
    private javax.swing.JLabel jLabel1_numberUser;
    private javax.swing.JLabel jLabel1_result;
    private javax.swing.JLabel jLabel1_sum;
    private javax.swing.JLabel jLabel2_failedAttempts;
    private javax.swing.JLabel jLabel2_numRandom2;
    private javax.swing.JLabel jLabel3_attempts;
    private javax.swing.JLabel jLabel3_equals;
    private javax.swing.JLabel jLabel_sumNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_frame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1_numberUser;
    private javax.swing.JTextArea sumNumber_TextArea;
    // End of variables declaration//GEN-END:variables
}
